name: "Flux Kontext Node"
description: "Image editing with Flux Kontext AI models via Replicate API"
author: "Leonardo Miramondi"
title: "Flux Kontext ComfyUI Node"
reference: "https://github.com/leonardomiramondi/flux-kontext-comfyui"
files:
- "flux_context_node.py"
- "__init__.py"
- "requirements.txt"
install_type: "git-clone"
description: "Advanced image editing with Flux Kontext models"
nodename_pattern: "FluxKontext"
pip: 
  - "requests>=2.25.0"
  - "Pillow>=8.0.0"
js_path: "" 