name: Test Installation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test import
      run: |
        python -c "from flux_replicate_node import FluxReplicateNode; print('✅ Import successful')"
    
    - name: Test node initialization
      run: |
        python -c "
        from flux_replicate_node import FluxReplicateNode
        node = FluxReplicateNode()
        input_types = node.INPUT_TYPES()
        assert 'required' in input_types
        assert 'optional' in input_types
        print('✅ Node initialization successful')
        " 